name: Deploy

on:
  push:
    branches: [84-ci-cd]
  workflow_dispatch:

jobs:
  sync:
    uses: ./.github/workflows/deploy-repo.yml
    secrets: inherit

  deploy-postgres:
    needs: sync
    uses: ./.github/workflows/deploy-postgres.yml
    secrets: inherit

  deploy-kafka:
    needs: sync
    uses: ./.github/workflows/deploy-kafka.yml
    secrets: inherit

  deploy-club-service:
    needs: [deploy-postgres, deploy-kafka]
    uses: ./.github/workflows/deploy-club-service.yml
    secrets: inherit

  deploy-event-service:
    needs: [deploy-postgres, deploy-kafka]
    uses: ./.github/workflows/deploy-event-service.yml
    secrets: inherit