name: Deploy Postgres

on:
  
  workflow_run:
    workflows: [ "Sync Repository to Server" ]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy-postgres:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Postgres
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd /opt/wingding &&
            docker compose pull postgres &&
            POSTGRES_USER='${{ secrets.POSTGRES_USER }}' \
            POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}' \
            docker compose up -d postgres
          "